project_id = "qlnbergwjfrmgkjhrbkj"

[functions.create-checkout]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.download-asset]
verify_jwt = false

[functions.check-nsfw]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-otp-email]
verify_jwt = false

[functions.custom-password-reset]
verify_jwt = false

[functions.send-application-confirmation]
verify_jwt = false

[functions.send-application-status-update]
verify_jwt = false
