// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the currently authenticated Eclipse user's id and email.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const payload = { userId: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(payload) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.23.8";
function anonClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_products_default = defineTool2({
  name: "search_products",
  title: "Search products",
  description: "Search Eclipse's public Roblox marketplace catalog by keyword. Returns id, title, price (GBP), category and slug.",
  inputSchema: {
    query: z.string().trim().min(1).max(120).describe("Search keywords, e.g. 'sports car', 'city map'."),
    limit: z.number().int().min(1).max(25).optional().describe("Max results (1\u201325, default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, _ctx) => {
    const supabase = anonClient();
    const max = limit ?? 10;
    const { data, error } = await supabase.from("products").select("id, title, slug, price, category, thumbnail_url").eq("status", "published").ilike("title", `%${query}%`).limit(max);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-orders.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.57.4";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.23.8";
function supabaseForUser(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_orders_default = defineTool3({
  name: "get_my_orders",
  title: "Get my orders",
  description: "List the signed-in user's recent Eclipse orders. RLS scopes results to the caller.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max orders (1\u201350, default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("orders").select("id, total, currency, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 10);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-my-wishlist.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@2.57.4";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.23.8";
function supabaseForUser2(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_my_wishlist_default = defineTool4({
  name: "get_my_wishlist",
  title: "Get my wishlist",
  description: "List the signed-in user's wishlisted products.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max items (1\u201350, default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("wishlist_items").select("id, product_id, created_at, products(title, slug, price)").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { wishlist: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qlnbergwjfrmgkjhrbkj";
var mcp_default = defineMcp({
  name: "eclipse-mcp",
  title: "Eclipse Marketplace",
  version: "0.1.0",
  instructions: "Tools for the Eclipse Roblox marketplace. Use `search_products` to browse the public catalog; `whoami`, `get_my_orders` and `get_my_wishlist` act as the signed-in Eclipse user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, search_products_default, get_my_orders_default, get_my_wishlist_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
